import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#20201f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "surface-tint": "#00dce5",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#b9caca",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#849495",
        "outline-variant": "#3a494a",
        primary: "#e9feff",
        "on-primary": "#003739",
        "primary-container": "#00f5ff",
        "on-primary-container": "#006c71",
        "inverse-primary": "#00696e",
        "primary-fixed": "#63f7ff",
        "primary-fixed-dim": "#00dce5",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#004f53",
        secondary: "#b8c3ff",
        "on-secondary": "#002388",
        "secondary-container": "#0043eb",
        "on-secondary-container": "#c6ceff",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b8c3ff",
        tertiary: "#ebffea",
        "on-tertiary": "#003919",
        "tertiary-container": "#7ef5a0",
        "on-tertiary-container": "#007037",
        "tertiary-fixed": "#83fba5",
        "tertiary-fixed-dim": "#66dd8b",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0a0a0a",
        "on-background": "#e5e2e1",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "sans-serif"],
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "technical-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        margin: "24px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      maxWidth: {
        container: "1440px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        "glow-cyan": "0 0 20px rgba(0, 220, 229, 0.15)",
        "glow-cyan-lg": "0 0 40px rgba(0, 220, 229, 0.25)",
      },
      keyframes: {
        scan: {
          "0%": { top: "0", opacity: "0" },
          "5%": { opacity: "1" },
          "95%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        pulse: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(1.1)" },
        },
        "radar-sweep": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "dash-flow": {
          to: { strokeDashoffset: "-16" },
        },
      },
      animation: {
        scan: "scan 4s linear infinite",
        "node-pulse": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "radar-sweep": "radar-sweep 4s linear infinite",
        "dash-flow": "dash-flow 1s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
